#!/usr/bin/env python3
"""
FlashOcc official occupancy visualizer, simplified for qualitative comparison.

Based on tools/analysis_tools/vis_occ.py:
- keeps the official voxel conversion and front-overlook Open3D viewpoint;
- uses the requested semantic color palette;
- saves Prediction and Ground Truth separately;
- saves the six original camera images separately;
- does not generate a collage or video;
- associates predictions with samples through scene_name/sample_token/pred.npz.
"""

import argparse
import json
import os
import pickle
from pathlib import Path
from typing import Any, Dict, List, Optional, Sequence, Tuple

import cv2
import mmcv
import numpy as np
import open3d as o3d
import torch


FREE_LABEL = 17

VOXEL_SIZE = [0.4, 0.4, 0.4]
POINT_CLOUD_RANGE = [-40.0, -40.0, -1.0, 40.0, 40.0, 5.4]
SPATIAL_SHAPE = [200, 200, 16]

CAMERA_NAMES = [
    "CAM_FRONT_LEFT",
    "CAM_FRONT",
    "CAM_FRONT_RIGHT",
    "CAM_BACK_LEFT",
    "CAM_BACK",
    "CAM_BACK_RIGHT",
]

# Class IDs:
# 0 others, 1 barrier, 2 bicycle, 3 bus, 4 car,
# 5 construction_vehicle, 6 motorcycle, 7 pedestrian,
# 8 traffic_cone, 9 trailer, 10 truck, 11 driveable_surface,
# 12 other_flat, 13 sidewalk, 14 terrain, 15 manmade,
# 16 vegetation, 17 free.
#
# This palette matches the successful weather-scene visualization.
COLORMAP_TO_COLORS = np.asarray(
    [
        [30, 30, 30, 255],       # 0  others
        [255, 120, 50, 255],     # 1  barrier
        [248, 188, 205, 255],    # 2  bicycle
        [252, 235, 10, 255],     # 3  bus
        [30, 145, 240, 255],     # 4  car
        [15, 215, 228, 255],     # 5  construction vehicle
        [195, 170, 0, 255],      # 6  motorcycle
        [240, 20, 20, 255],      # 7  pedestrian
        [244, 225, 120, 255],    # 8  traffic cone
        [132, 70, 14, 255],      # 9  trailer
        [145, 55, 230, 255],     # 10 truck
        [248, 35, 240, 255],     # 11 driveable surface
        [160, 0, 88, 255],       # 12 other flat
        [78, 0, 86, 255],        # 13 sidewalk
        [145, 220, 85, 255],     # 14 terrain
        [205, 205, 220, 255],    # 15 manmade
        [0, 178, 18, 255],       # 16 vegetation
        [255, 255, 255, 255],    # 17 free; not rendered
    ],
    dtype=np.float32,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Render FlashOcc prediction, GT, and six input images as "
            "independent files using the official front-overlook viewpoint."
        )
    )
    parser.add_argument(
        "res",
        help=(
            "Prediction root. Expected file layout: "
            "res/scene_name/sample_token/pred.npz"
        ),
    )
    parser.add_argument(
        "--root-path",
        "--root_path",
        dest="root_path",
        default="./data/nuscenes",
        help="nuScenes data root.",
    )
    parser.add_argument(
        "--info-path",
        default=None,
        help=(
            "Annotation PKL. Default: "
            "<root-path>/bevdetv2-nuscenes_infos_<version>.pkl"
        ),
    )
    parser.add_argument(
        "--version",
        default="val",
        help="Used only when --info-path is omitted.",
    )
    parser.add_argument(
        "--save-path",
        "--save_path",
        dest="save_path",
        default="./vis_occ_official",
        help="Output directory.",
    )
    parser.add_argument(
        "--vis-frames",
        type=int,
        default=30,
        help="Number of samples to render when no explicit selection is given.",
    )
    parser.add_argument(
        "--indices",
        default=None,
        help="Comma-separated indices in the annotation PKL, e.g. 0,10,25.",
    )
    parser.add_argument(
        "--tokens-file",
        default=None,
        help="Text file containing one sample token per line.",
    )
    parser.add_argument(
        "--subset-meta",
        default=None,
        help=(
            "Random-subset JSON generated by build_random_val_subset.py. "
            "Its selected_tokens are rendered in the recorded order."
        ),
    )
    parser.add_argument(
        "--mask-mode",
        choices=("camera", "lidar", "none"),
        default="camera",
        help="Visibility mask applied identically to Prediction and GT.",
    )
    parser.add_argument(
        "--render-width",
        type=int,
        default=2560,
        help="Open3D render-window width.",
    )
    parser.add_argument(
        "--render-height",
        type=int,
        default=1440,
        help="Open3D render-window height.",
    )
    parser.add_argument(
        "--zoom",
        type=float,
        default=0.08,
        help="Official front-overlook zoom.",
    )
    parser.add_argument(
        "--hidden",
        action="store_true",
        help="Request a hidden Open3D window when supported.",
    )
    parser.add_argument(
        "--interactive",
        action="store_true",
        help="Open the interactive Open3D window before each capture.",
    )
    parser.add_argument(
        "--no-voxel-edges",
        action="store_true",
        help="Disable black voxel edge lines.",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Regenerate samples whose outputs already exist.",
    )
    parser.add_argument(
        "--skip-missing",
        action="store_true",
        help="Skip samples with missing prediction or image files.",
    )
    return parser.parse_args()


def normalize_grid(
    array: np.ndarray,
    expected_shape: Tuple[int, int, int] = tuple(SPATIAL_SHAPE),
    name: str = "grid",
) -> np.ndarray:
    grid = np.asarray(array)
    grid = np.squeeze(grid)

    if grid.shape == expected_shape:
        return grid

    permutations = (
        (0, 1, 2),
        (0, 2, 1),
        (1, 0, 2),
        (1, 2, 0),
        (2, 0, 1),
        (2, 1, 0),
    )
    matches = [
        permutation
        for permutation in permutations
        if tuple(grid.shape[index] for index in permutation) == expected_shape
    ]
    if len(matches) == 1:
        return np.transpose(grid, matches[0])

    raise ValueError(
        f"{name} has unsupported shape {grid.shape}; expected {expected_shape} "
        "or an unambiguous axis permutation."
    )


def voxel2points(
    voxel: torch.Tensor,
    occ_show: torch.Tensor,
    voxel_size: Sequence[float],
) -> Tuple[torch.Tensor, torch.Tensor, Tuple[torch.Tensor, ...]]:
    """Official FlashOcc voxel-index to metric-coordinate conversion."""
    occ_idx = torch.where(occ_show)
    points = torch.cat(
        (
            occ_idx[0][:, None] * voxel_size[0] + POINT_CLOUD_RANGE[0],
            occ_idx[1][:, None] * voxel_size[1] + POINT_CLOUD_RANGE[1],
            occ_idx[2][:, None] * voxel_size[2] + POINT_CLOUD_RANGE[2],
        ),
        dim=1,
    )
    return points, voxel[occ_idx], occ_idx


def voxel_profile(
    voxel: torch.Tensor,
    voxel_size: Sequence[float],
) -> torch.Tensor:
    centers = torch.cat(
        (
            voxel[:, :2],
            voxel[:, 2][:, None] - voxel_size[2] / 2,
        ),
        dim=1,
    )
    dtype = centers.dtype
    device = centers.device
    count = centers.shape[0]
    wlh = torch.cat(
        (
            torch.full(
                (count, 1),
                float(voxel_size[0]),
                dtype=dtype,
                device=device,
            ),
            torch.full(
                (count, 1),
                float(voxel_size[1]),
                dtype=dtype,
                device=device,
            ),
            torch.full(
                (count, 1),
                float(voxel_size[2]),
                dtype=dtype,
                device=device,
            ),
        ),
        dim=1,
    )
    yaw = torch.zeros_like(centers[:, 0:1])
    return torch.cat((centers, wlh, yaw), dim=1)


def my_compute_box_3d(
    center: torch.Tensor,
    size: torch.Tensor,
    heading_angle: torch.Tensor,
) -> torch.Tensor:
    del heading_angle
    center = center.clone()
    h, w, length = size[:, 2], size[:, 0], size[:, 1]
    center[:, 2] = center[:, 2] + h / 2

    length = (length / 2).unsqueeze(1)
    w = (w / 2).unsqueeze(1)
    h = (h / 2).unsqueeze(1)

    x_corners = torch.cat(
        (-length, length, length, -length, -length, length, length, -length),
        dim=1,
    )[..., None]
    y_corners = torch.cat(
        (w, w, -w, -w, w, w, -w, -w),
        dim=1,
    )[..., None]
    z_corners = torch.cat(
        (h, h, h, h, -h, -h, -h, -h),
        dim=1,
    )[..., None]

    corners_3d = torch.cat((x_corners, y_corners, z_corners), dim=2)
    corners_3d[..., 0] += center[:, 0:1]
    corners_3d[..., 1] += center[:, 1:2]
    corners_3d[..., 2] += center[:, 2:3]
    return corners_3d


def create_voxel_edge_lines(
    bbox_corners: torch.Tensor,
) -> Tuple[np.ndarray, np.ndarray]:
    bases = torch.arange(
        0,
        bbox_corners.shape[0] * 8,
        8,
        dtype=torch.long,
    )
    edges = torch.tensor(
        [
            [0, 1],
            [1, 2],
            [2, 3],
            [3, 0],
            [4, 5],
            [5, 6],
            [6, 7],
            [7, 4],
            [0, 4],
            [1, 5],
            [2, 6],
            [3, 7],
        ],
        dtype=torch.long,
    )
    edges = edges.reshape(1, 12, 2).repeat(
        bbox_corners.shape[0],
        1,
        1,
    )
    edges = edges + bases[:, None, None]
    return (
        bbox_corners.reshape(-1, 3).numpy(),
        edges.reshape(-1, 2).numpy(),
    )


def add_occ_geometry(
    vis: Any,
    occ_state: np.ndarray,
    occ_show: np.ndarray,
    voxel_size: Sequence[float],
    draw_edges: bool,
) -> int:
    state_tensor = torch.from_numpy(occ_state)
    show_tensor = torch.from_numpy(occ_show.astype(np.bool_))

    points, labels, _ = voxel2points(
        state_tensor,
        show_tensor,
        voxel_size,
    )
    if points.shape[0] == 0:
        raise RuntimeError("No occupied voxels remain after applying the mask.")

    colors = COLORMAP_TO_COLORS / 255.0
    label_indices = torch.remainder(
        labels.to(torch.long),
        len(colors),
    ).numpy()
    point_colors = colors[label_indices, :3]

    point_cloud = o3d.geometry.PointCloud()
    point_cloud.points = o3d.utility.Vector3dVector(points.numpy())
    point_cloud.colors = o3d.utility.Vector3dVector(point_colors)

    voxel_grid = o3d.geometry.VoxelGrid.create_from_point_cloud(
        point_cloud,
        voxel_size=float(np.mean(voxel_size)),
    )
    vis.add_geometry(voxel_grid)

    if draw_edges:
        bboxes = voxel_profile(points, voxel_size)
        corners = my_compute_box_3d(
            bboxes[:, 0:3],
            bboxes[:, 3:6],
            bboxes[:, 6:7],
        )
        edge_points, edge_indices = create_voxel_edge_lines(corners)
        line_set = o3d.geometry.LineSet()
        line_set.points = o3d.utility.Vector3dVector(edge_points)
        line_set.lines = o3d.utility.Vector2iVector(edge_indices)
        line_set.paint_uniform_color((0.0, 0.0, 0.0))
        vis.add_geometry(line_set)

    # Preserve the official coordinate-frame display.
    mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(
        size=1.0,
        origin=[0.0, 0.0, 0.0],
    )
    vis.add_geometry(mesh_frame)
    return int(points.shape[0])


def set_official_front_view(vis: Any, zoom: float) -> None:
    """Official FlashOcc front-overlook camera parameters."""
    view_control = vis.get_view_control()
    view_control.set_lookat(np.asarray([-0.185, 0.513, 3.485]))
    view_control.set_front(np.asarray([-0.974, -0.055, 0.221]))
    view_control.set_up(np.asarray([0.221, 0.014, 0.975]))
    view_control.set_zoom(float(zoom))

    render_option = vis.get_render_option()
    render_option.background_color = np.asarray([1.0, 1.0, 1.0])
    render_option.line_width = 5.0


def capture_occ(
    vis: Any,
    occ_state: np.ndarray,
    occ_show: np.ndarray,
    output_path: Path,
    voxel_size: Sequence[float],
    zoom: float,
    draw_edges: bool,
    interactive: bool,
) -> int:
    vis.clear_geometries()
    count = add_occ_geometry(
        vis=vis,
        occ_state=occ_state,
        occ_show=occ_show,
        voxel_size=voxel_size,
        draw_edges=draw_edges,
    )
    set_official_front_view(vis, zoom)

    for _ in range(8):
        vis.poll_events()
        vis.update_renderer()

    if interactive:
        vis.run()
        set_official_front_view(vis, zoom)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    success = vis.capture_screen_image(
        str(output_path),
        do_render=True,
    )
    if success is False:
        raise RuntimeError(f"Open3D failed to save {output_path}")
    return count


def create_visualizer(
    width: int,
    height: int,
    hidden: bool,
) -> Any:
    vis = o3d.visualization.VisualizerWithKeyCallback()
    try:
        created = vis.create_window(
            width=int(width),
            height=int(height),
            visible=not hidden,
        )
    except TypeError:
        created = vis.create_window(
            width=int(width),
            height=int(height),
        )
    if created is False:
        raise RuntimeError("Open3D failed to create a visualization window.")
    return vis


def load_infos(info_path: Path) -> List[Dict[str, Any]]:
    with info_path.open("rb") as handle:
        payload = pickle.load(handle)
    if isinstance(payload, dict) and isinstance(payload.get("infos"), list):
        return list(payload["infos"])
    if isinstance(payload, list):
        return list(payload)
    raise TypeError(f"Unsupported annotation structure: {info_path}")


def parse_indices(specification: str, sample_count: int) -> List[int]:
    indices: List[int] = []
    for item in specification.split(","):
        item = item.strip()
        if not item:
            continue
        index = int(item)
        if not 0 <= index < sample_count:
            raise IndexError(
                f"Index {index} is outside [0, {sample_count - 1}]"
            )
        indices.append(index)
    return indices


def load_tokens_file(path: Path) -> List[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]


def select_infos(
    infos: List[Dict[str, Any]],
    args: argparse.Namespace,
) -> List[Tuple[int, Dict[str, Any]]]:
    token_to_item = {
        str(info["token"]): (index, info)
        for index, info in enumerate(infos)
    }

    if args.subset_meta:
        metadata = json.loads(
            Path(args.subset_meta).read_text(encoding="utf-8")
        )
        tokens = [str(token) for token in metadata["selected_tokens"]]
        missing = [token for token in tokens if token not in token_to_item]
        if missing:
            raise KeyError(
                f"{len(missing)} subset tokens are absent from the annotation "
                f"PKL; first missing token: {missing[0]}"
            )
        return [token_to_item[token] for token in tokens]

    if args.tokens_file:
        tokens = load_tokens_file(Path(args.tokens_file))
        missing = [token for token in tokens if token not in token_to_item]
        if missing:
            raise KeyError(
                f"{len(missing)} requested tokens are absent from the annotation "
                f"PKL; first missing token: {missing[0]}"
            )
        return [token_to_item[token] for token in tokens]

    if args.indices:
        indices = parse_indices(args.indices, len(infos))
        return [(index, infos[index]) for index in indices]

    count = min(max(int(args.vis_frames), 0), len(infos))
    return [(index, infos[index]) for index in range(count)]


def resolve_existing_path(
    path_value: str,
    root_path: Path,
) -> Path:
    path = Path(path_value)
    candidates = [path]
    if not path.is_absolute():
        candidates.extend(
            [
                root_path / path,
                Path.cwd() / path,
            ]
        )
    for candidate in candidates:
        if candidate.is_file():
            return candidate
    return candidates[0]


def save_camera_images(
    info: Dict[str, Any],
    output_dir: Path,
    root_path: Path,
    skip_missing: bool,
) -> None:
    for camera_name in CAMERA_NAMES:
        camera_info = info["cams"][camera_name]
        image_path = resolve_existing_path(
            str(camera_info["data_path"]),
            root_path,
        )
        image = cv2.imread(str(image_path), cv2.IMREAD_COLOR)
        if image is None:
            message = f"Cannot read {camera_name} image: {image_path}"
            if skip_missing:
                print(f"[WARN] {message}")
                continue
            raise FileNotFoundError(message)

        output_file = output_dir / f"{camera_name}.png"
        if not cv2.imwrite(str(output_file), image):
            raise RuntimeError(f"Failed to save {output_file}")


def load_visibility_mask(
    gt_data: Any,
    mask_mode: str,
    expected_shape: Tuple[int, int, int],
) -> np.ndarray:
    if mask_mode == "none":
        return np.ones(expected_shape, dtype=np.bool_)
    key = "mask_camera" if mask_mode == "camera" else "mask_lidar"
    return normalize_grid(
        gt_data[key],
        expected_shape=expected_shape,
        name=key,
    ).astype(np.bool_)


def main() -> None:
    args = parse_args()

    root_path = Path(args.root_path)
    info_path = (
        Path(args.info_path)
        if args.info_path
        else root_path / f"bevdetv2-nuscenes_infos_{args.version}.pkl"
    )
    if not info_path.is_file():
        raise FileNotFoundError(f"Annotation PKL not found: {info_path}")

    prediction_root = Path(args.res)
    if not prediction_root.is_dir():
        raise NotADirectoryError(
            f"Prediction root does not exist: {prediction_root}"
        )

    save_root = Path(args.save_path)
    save_root.mkdir(parents=True, exist_ok=True)

    infos = load_infos(info_path)
    selected_infos = select_infos(infos, args)

    print(f"[INFO] Annotation samples : {len(infos)}")
    print(f"[INFO] Selected samples   : {len(selected_infos)}")
    print(f"[INFO] Prediction root    : {prediction_root}")
    print(f"[INFO] Output root        : {save_root}")
    print(f"[INFO] Mask mode          : {args.mask_mode}")
    print("[INFO] Output files       : pred_front_overlook.png, "
          "gt_front_overlook.png, six CAM_*.png")

    vis = create_visualizer(
        width=args.render_width,
        height=args.render_height,
        hidden=args.hidden,
    )

    manifest_rows: List[Dict[str, Any]] = []
    try:
        for rank, (dataset_index, info) in enumerate(
            selected_infos,
            start=1,
        ):
            scene_name = str(info["scene_name"])
            sample_token = str(info["token"])
            output_dir = save_root / scene_name / sample_token

            required_outputs = [
                output_dir / "pred_front_overlook.png",
                output_dir / "gt_front_overlook.png",
                *[
                    output_dir / f"{camera_name}.png"
                    for camera_name in CAMERA_NAMES
                ],
            ]
            if (
                not args.overwrite
                and all(path.is_file() for path in required_outputs)
            ):
                print(
                    f"[SKIP] {rank:03d}/{len(selected_infos):03d} "
                    f"{scene_name} {sample_token}"
                )
                continue

            pred_occ_path = (
                prediction_root
                / scene_name
                / sample_token
                / "pred.npz"
            )
            gt_occ_path = (
                root_path
                / str(info["occ_path"])
                / "labels.npz"
            )

            if not pred_occ_path.is_file():
                message = f"Prediction not found: {pred_occ_path}"
                if args.skip_missing:
                    print(f"[WARN] {message}")
                    continue
                raise FileNotFoundError(message)
            if not gt_occ_path.is_file():
                message = f"GT not found: {gt_occ_path}"
                if args.skip_missing:
                    print(f"[WARN] {message}")
                    continue
                raise FileNotFoundError(message)

            pred_payload = np.load(pred_occ_path)
            if "pred" not in pred_payload:
                raise KeyError(f"'pred' is absent from {pred_occ_path}")
            pred_occ = normalize_grid(
                pred_payload["pred"],
                name="prediction",
            )

            gt_data = np.load(gt_occ_path)
            gt_occ = normalize_grid(
                gt_data["semantics"],
                expected_shape=tuple(pred_occ.shape),
                name="GT semantics",
            )
            visibility_mask = load_visibility_mask(
                gt_data,
                args.mask_mode,
                expected_shape=tuple(pred_occ.shape),
            )

            pred_show = np.logical_and(
                pred_occ != FREE_LABEL,
                visibility_mask,
            )
            gt_show = np.logical_and(
                gt_occ != FREE_LABEL,
                visibility_mask,
            )

            output_dir.mkdir(parents=True, exist_ok=True)
            save_camera_images(
                info=info,
                output_dir=output_dir,
                root_path=root_path,
                skip_missing=args.skip_missing,
            )

            pred_count = capture_occ(
                vis=vis,
                occ_state=pred_occ,
                occ_show=pred_show,
                output_path=output_dir / "pred_front_overlook.png",
                voxel_size=VOXEL_SIZE,
                zoom=args.zoom,
                draw_edges=not args.no_voxel_edges,
                interactive=args.interactive,
            )
            gt_count = capture_occ(
                vis=vis,
                occ_state=gt_occ,
                occ_show=gt_show,
                output_path=output_dir / "gt_front_overlook.png",
                voxel_size=VOXEL_SIZE,
                zoom=args.zoom,
                draw_edges=not args.no_voxel_edges,
                interactive=args.interactive,
            )

            metadata = {
                "dataset_index": dataset_index,
                "scene_name": scene_name,
                "sample_token": sample_token,
                "prediction_file": str(pred_occ_path),
                "gt_file": str(gt_occ_path),
                "mask_mode": args.mask_mode,
                "prediction_shape": list(map(int, pred_occ.shape)),
                "gt_shape": list(map(int, gt_occ.shape)),
                "prediction_voxels": pred_count,
                "gt_voxels": gt_count,
            }
            (output_dir / "metadata.json").write_text(
                json.dumps(metadata, indent=2, ensure_ascii=False),
                encoding="utf-8",
            )
            manifest_rows.append(metadata)

            print(
                f"[DONE] {rank:03d}/{len(selected_infos):03d} "
                f"index={dataset_index} scene={scene_name} "
                f"token={sample_token[:16]} "
                f"pred={pred_count} gt={gt_count}"
            )
    finally:
        vis.clear_geometries()
        vis.destroy_window()

    mmcv.dump(
        manifest_rows,
        str(save_root / "visualized_samples.pkl"),
    )
    print(
        f"[INFO] Manifest saved: "
        f"{save_root / 'visualized_samples.pkl'}"
    )


if __name__ == "__main__":
    main()
